


export const metadata = {
  title: "Construz || Responsive Next Template",
  description: "Generated by create next app",
  icons: {
    icon: [
      { rel: "icon", type: "image/png", sizes: "32x32", url: "/favicon.png" },
    ],
    apple: [
      { rel: "apple-touch-icon", sizes: "180x180", url: "/favicon.png" },
    ],
    shortcut: [
      { rel: "shortcut icon", url: "/favicon.png" },
    ],
  },
};
import "~/public/main-assets/css/fonts.css";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
